### ISSUE TITLE
make fails with cuda set as backend

### ISSUE THREAD

**Issue by Tiltedprogrammer** [AnyDSL/anyseq#1]
Hi, I am currently learning some of AnyDSL and checked out this project as a reference example of how things should work. However I ran into troubles while trying to make the project to 3 different backends. CPU backend went fine but 2 others failed.
![image](https://user-images.githubusercontent.com/22172264/62289221-d08bd680-b466-11e9-8e39-c2d08504ef5d.png)
I'm not experienced in cuda and anydsl yet, so it seems I can't handle this myself at this point.

Build for avx failed too, but I am personally more interested in cuda.

![image](https://user-images.githubusercontent.com/22172264/62289532-9ff86c80-b467-11e9-97bd-11ba3cdbc817.png)

**Comment by muellan** [comment]
Hi,
if you are just learning AnyDSL, this project - which is still under development (interfaces etc. are in constant flux, ...) - maybe not such a good starting point. And I'm aware of a number of issues that popped up due to newer AnyDSL and/or LLVM versions.
If you want a much more stable and matured project, you could check out [Stincilla](https://github.com/AnyDSL/stincilla).

**Comment by richardmembarth** [comment]
@Tiltedprogrammer do you have minimal working examples to reproduce the errors?
Otherwise it's hard to guess what's going wrong, in particular for the second error.

The first error tells you that you use a pointer to an `int` on the GPU, which is not supported:
```rust
let mut i = 0;
with cuda() {
    i = 42;
}
```
Currently, we support and encourage only the manipulation of arrays on the GPU with explicit data management.

**Comment by richardmembarth** [comment]
The second error is actually documented on RV's wiki:
https://github.com/cdl-saarland/rv/wiki/Troubleshooting
